swagger: '2.0'
info:
  version: 0.8.0
  title: Foam API
host: api-beta.foam.space
schemes:
  - https
paths:
  /index:
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      responses:
        '200':
          schema:
            description: The HTML file of the SpatialIndex
            example: <html><head>...</head></html>
            type: string
          description: ''
      security:
        - JwtSecurity: []
  /beacon:
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      parameters:
        - format: double
          in: query
          name: lat_min
          type: number
        - format: double
          in: query
          name: lon_min
          type: number
        - format: double
          in: query
          name: lat_max
          type: number
        - format: double
          in: query
          name: lon_max
          type: number
        - format: double
          in: query
          name: zoom
          type: number
      responses:
        '200':
          schema:
            items:
              description: A Beacon contract
              required:
                - beaconTransactionHash
                - beaconBeaconAddress
                - beaconFactoryAddress
                - beaconName
                - beaconGeohash
              properties:
                beaconTransactionHash:
                  type: string
                beaconBeaconAddress:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                beaconFactoryAddress:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                beaconName:
                  type: string
                beaconGeohash:
                  example: lpb2b3kosmdi53dg
                  format: base32
                  type: string
              example:
                beaconTransactionHash: >-
                  0x3857646540475d9f562e83f61131ed14b39352bb9998abfaad6315289c178d20
                beaconName: NYC Community Beacon
                beaconGeohash: t3k6pt76vc4g0w32ymp
                beaconBeaconAddress: '0xe8f5942323ff1bfc6a0062b3b16d122d449f64e3'
                beaconFactoryAddress: '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
              type: object
            type: array
          description: ''
        '400':
          description: Invalid `zoom` or `lon_max` or `lat_max` or `lon_min` or `lat_min`
      security:
        - JwtSecurity: []
  '/beacon/{address}':
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      parameters:
        - required: true
          in: path
          name: address
          type: string
      responses:
        '200':
          schema:
            description: A Beacon contract
            required:
              - beaconTransactionHash
              - beaconBeaconAddress
              - beaconFactoryAddress
              - beaconName
              - beaconGeohash
            properties:
              beaconTransactionHash:
                type: string
              beaconBeaconAddress:
                example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                format: base16
                type: string
              beaconFactoryAddress:
                example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                format: base16
                type: string
              beaconName:
                type: string
              beaconGeohash:
                example: lpb2b3kosmdi53dg
                format: base32
                type: string
            example:
              beaconTransactionHash: >-
                0x3857646540475d9f562e83f61131ed14b39352bb9998abfaad6315289c178d20
              beaconName: NYC Community Beacon
              beaconGeohash: t3k6pt76vc4g0w32ymp
              beaconBeaconAddress: '0xe8f5942323ff1bfc6a0062b3b16d122d449f64e3'
              beaconFactoryAddress: '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
            type: object
          description: ''
        '404':
          description: '`address` not found'
      security:
        - JwtSecurity: []
  '/beacon/{address}/token_transfers':
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      parameters:
        - required: true
          in: path
          name: address
          type: string
      responses:
        '200':
          schema:
            items:
              description: A TokenTransfer event and the corresponding value
              required:
                - ttAddr
                - ttFromAddr
                - ttBlockNumber
                - ttDepositedValue
                - currentValue
              properties:
                ttAddr:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                ttFromAddr:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                ttBlockNumber:
                  description: A hexstring
                  example: '0xabba666deadbeef'
                  format: base16
                  type: string
                ttDepositedValue:
                  description: A hexstring
                  example: '0xabba666deadbeef'
                  format: base16
                  type: string
                currentValue:
                  description: A hexstring
                  example: '0xabba666deadbeef'
                  format: base16
                  type: string
              example:
                ttAddr: '0xe8f5942323ff1bfc6a0062b3b16d122d449f64e3'
                ttBlockNumber: 31eba01
                ttDepositedValue: 7b
                currentValue: cb9cb941a
                ttFromAddr: '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
              type: object
            type: array
          description: ''
        '404':
          description: '`address` not found'
      security:
        - JwtSecurity: []
  '/beacon/{address}/shareholders':
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      parameters:
        - required: true
          in: path
          name: address
          type: string
      responses:
        '200':
          schema:
            items:
              description: The balance for a given address
              required:
                - shareholderAddress
                - shareholderValue
              properties:
                shareholderAddress:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                shareholderValue:
                  description: A hexstring
                  example: '0xabba666deadbeef'
                  format: base16
                  type: string
              example:
                shareholderAddress: '0xe8f5942323ff1bfc6a0062b3b16d122d449f64e3'
                shareholderValue: cb9cb941a
              type: object
            type: array
          description: ''
        '404':
          description: '`address` not found'
      security:
        - JwtSecurity: []
  /tokens:
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      responses:
        '200':
          schema:
            description: A hexstring
            example: '0xabba666deadbeef'
            format: base16
            type: string
          description: ''
      security:
        - JwtSecurity: []
  /token_transfers:
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      responses:
        '200':
          schema:
            items:
              description: A TokenTransfer event and the corresponding value
              required:
                - ttAddr
                - ttFromAddr
                - ttBlockNumber
                - ttDepositedValue
                - currentValue
              properties:
                ttAddr:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                ttFromAddr:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                ttBlockNumber:
                  description: A hexstring
                  example: '0xabba666deadbeef'
                  format: base16
                  type: string
                ttDepositedValue:
                  description: A hexstring
                  example: '0xabba666deadbeef'
                  format: base16
                  type: string
                currentValue:
                  description: A hexstring
                  example: '0xabba666deadbeef'
                  format: base16
                  type: string
              example:
                ttAddr: '0xe8f5942323ff1bfc6a0062b3b16d122d449f64e3'
                ttBlockNumber: 31eba01
                ttDepositedValue: 7b
                currentValue: cb9cb941a
                ttFromAddr: '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
              type: object
            type: array
          description: ''
      security:
        - JwtSecurity: []
  /csc:
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      parameters:
        - format: double
          in: query
          name: lat_min
          type: number
        - format: double
          in: query
          name: lon_min
          type: number
        - format: double
          in: query
          name: lat_max
          type: number
        - format: double
          in: query
          name: lon_max
          type: number
        - format: double
          in: query
          name: zoom
          type: number
        - in: query
          name: registrant
          type: string
      responses:
        '200':
          schema:
            items:
              description: A CryptoSpatialCoordinate
              required:
                - cSCTransactionHash
                - cSCCsc
                - cSCContractAddress
                - cSCRegistrantAddress
                - cSCGeohash
              properties:
                cSCTransactionHash:
                  type: string
                cSCCsc:
                  type: string
                cSCContractAddress:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                cSCRegistrantAddress:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                cSCGeohash:
                  example: lpb2b3kosmdi53dg
                  format: base32
                  type: string
              example:
                cSCGeohash: t3k6pt76vc4g0w32ymp
                cSCTransactionHash: >-
                  0x3857646540475d9f562e83f61131ed14b39352bb9998abfaad6315289c178d20
                cSCContractAddress: '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
                cSCRegistrantAddress: '0x376dd6fc3c0071f4167092bd237e7a141767e4a3'
                cSCCsc: 060f28b8ab153c542bceff9c
              type: object
            type: array
          description: ''
        '400':
          description: >-
            Invalid `registrant` or `zoom` or `lon_max` or `lat_max` or
            `lon_min` or `lat_min`
      security:
        - JwtSecurity: []
  '/csc/{csc}':
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      parameters:
        - required: true
          in: path
          name: csc
          type: string
      responses:
        '200':
          schema:
            description: A CryptoSpatialCoordinate
            required:
              - cSCTransactionHash
              - cSCCsc
              - cSCContractAddress
              - cSCRegistrantAddress
              - cSCGeohash
            properties:
              cSCTransactionHash:
                type: string
              cSCCsc:
                type: string
              cSCContractAddress:
                example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                format: base16
                type: string
              cSCRegistrantAddress:
                example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                format: base16
                type: string
              cSCGeohash:
                example: lpb2b3kosmdi53dg
                format: base32
                type: string
            example:
              cSCGeohash: t3k6pt76vc4g0w32ymp
              cSCTransactionHash: >-
                0x3857646540475d9f562e83f61131ed14b39352bb9998abfaad6315289c178d20
              cSCContractAddress: '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
              cSCRegistrantAddress: '0x376dd6fc3c0071f4167092bd237e7a141767e4a3'
              cSCCsc: 060f28b8ab153c542bceff9c
            type: object
          description: ''
        '404':
          description: '`csc` not found'
      security:
        - JwtSecurity: []
  '/csc/by-registrant/{registrant}':
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      parameters:
        - required: true
          in: path
          name: registrant
          type: string
      responses:
        '200':
          schema:
            items:
              description: A CryptoSpatialCoordinate
              required:
                - cSCTransactionHash
                - cSCCsc
                - cSCContractAddress
                - cSCRegistrantAddress
                - cSCGeohash
              properties:
                cSCTransactionHash:
                  type: string
                cSCCsc:
                  type: string
                cSCContractAddress:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                cSCRegistrantAddress:
                  example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                  format: base16
                  type: string
                cSCGeohash:
                  example: lpb2b3kosmdi53dg
                  format: base32
                  type: string
              example:
                cSCGeohash: t3k6pt76vc4g0w32ymp
                cSCTransactionHash: >-
                  0x3857646540475d9f562e83f61131ed14b39352bb9998abfaad6315289c178d20
                cSCContractAddress: '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
                cSCRegistrantAddress: '0x376dd6fc3c0071f4167092bd237e7a141767e4a3'
                cSCCsc: 060f28b8ab153c542bceff9c
              type: object
            type: array
          description: ''
        '404':
          description: '`registrant` not found'
      security:
        - JwtSecurity: []
  /search:
    get:
      tags:
        - foam
      produces:
        - application/json;charset=utf-8
      parameters:
        - maximum: 9223372036854776000
          minimum: -9223372036854776000
          in: query
          name: offset
          type: integer
        - in: query
          name: query
          type: string
      responses:
        '200':
          schema:
            items:
              description: An elasticsearch result for beacons
              required:
                - shDocId
              properties:
                shDocId:
                  description: The identified for the DB
                  example: docid
                  type: string
                shScore:
                  format: double
                  type: number
                shSource:
                  example:
                    - NYC Beacon hub
                    - t3k6pt76wv36tqrdevu
                  minItems: 2
                  items:
                    - type: string
                    - example: lpb2b3kosmdi53dg
                      format: base32
                      type: string
                  maxItems: 2
                  type: array
              example:
                shScore: 2.2342
                shDocId: docid
                shSource:
                  - NYC Beacon hub
                  - t3k6pt76vc4g0w32ymp
              type: object
            type: array
          description: ''
        '400':
          description: Invalid `query` or `offset`
      security:
        - JwtSecurity: []
  /authenticate:
    post:
      tags:
        - foam
      consumes:
        - application/json;charset=utf-8
      produces:
        - application/json;charset=utf-8
      parameters:
        - required: true
          schema:
            description: The authentication parameters coming from Metamask or uPort
            required:
              - authenticationAddress
              - authenticationMessage
              - authenticationSignature
            properties:
              authenticationAddress:
                example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
                format: base16
                type: string
              authenticationMessage:
                description: A hexstring
                example: '0xabba666deadbeef'
                format: base16
                type: string
              authenticationSignature:
                description: A hexstring
                example: '0xabba666deadbeef'
                format: base16
                type: string
            example:
              authenticationSignature: 5f5daf8
              authenticationAddress: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
              authenticationMessage: bc11e1
            type: object
          in: body
          name: body
      responses:
        '200':
          schema:
            type: string
          description: ''
        '400':
          description: Invalid `body`
definitions:
  IndexString:
    description: The HTML file of the SpatialIndex
    example: <html><head>...</head></html>
    type: string
  Beacon:
    description: A Beacon contract
    required:
      - beaconTransactionHash
      - beaconBeaconAddress
      - beaconFactoryAddress
      - beaconName
      - beaconGeohash
    properties:
      beaconTransactionHash:
        type: string
      beaconBeaconAddress:
        example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
        format: base16
        type: string
      beaconFactoryAddress:
        example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
        format: base16
        type: string
      beaconName:
        type: string
      beaconGeohash:
        example: lpb2b3kosmdi53dg
        format: base32
        type: string
    example:
      beaconTransactionHash: '0x3857646540475d9f562e83f61131ed14b39352bb9998abfaad6315289c178d20'
      beaconName: NYC Community Beacon
      beaconGeohash: t3k6pt76vc4g0w32ymp
      beaconBeaconAddress: '0xe8f5942323ff1bfc6a0062b3b16d122d449f64e3'
      beaconFactoryAddress: '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
    type: object
  EthAddress:
    example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
    format: base16
    type: string
  Geohash:
    example: lpb2b3kosmdi53dg
    format: base32
    type: string
  TokenTransferWithCurrentValue:
    description: A TokenTransfer event and the corresponding value
    required:
      - ttAddr
      - ttFromAddr
      - ttBlockNumber
      - ttDepositedValue
      - currentValue
    properties:
      ttAddr:
        example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
        format: base16
        type: string
      ttFromAddr:
        example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
        format: base16
        type: string
      ttBlockNumber:
        description: A hexstring
        example: '0xabba666deadbeef'
        format: base16
        type: string
      ttDepositedValue:
        description: A hexstring
        example: '0xabba666deadbeef'
        format: base16
        type: string
      currentValue:
        description: A hexstring
        example: '0xabba666deadbeef'
        format: base16
        type: string
    example:
      ttAddr: '0xe8f5942323ff1bfc6a0062b3b16d122d449f64e3'
      ttBlockNumber: 31eba01
      ttDepositedValue: 7b
      currentValue: cb9cb941a
      ttFromAddr: '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
    type: object
  HexString:
    description: A hexstring
    example: '0xabba666deadbeef'
    format: base16
    type: string
  ShareHolder:
    description: The balance for a given address
    required:
      - shareholderAddress
      - shareholderValue
    properties:
      shareholderAddress:
        example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
        format: base16
        type: string
      shareholderValue:
        description: A hexstring
        example: '0xabba666deadbeef'
        format: base16
        type: string
    example:
      shareholderAddress: '0xe8f5942323ff1bfc6a0062b3b16d122d449f64e3'
      shareholderValue: cb9cb941a
    type: object
  CSC:
    description: A CryptoSpatialCoordinate
    required:
      - cSCTransactionHash
      - cSCCsc
      - cSCContractAddress
      - cSCRegistrantAddress
      - cSCGeohash
    properties:
      cSCTransactionHash:
        type: string
      cSCCsc:
        type: string
      cSCContractAddress:
        example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
        format: base16
        type: string
      cSCRegistrantAddress:
        example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
        format: base16
        type: string
      cSCGeohash:
        example: lpb2b3kosmdi53dg
        format: base32
        type: string
    example:
      cSCGeohash: t3k6pt76vc4g0w32ymp
      cSCTransactionHash: '0x3857646540475d9f562e83f61131ed14b39352bb9998abfaad6315289c178d20'
      cSCContractAddress: '0xea674fdde714fd979de3edf0f56aa9716b898ec8'
      cSCRegistrantAddress: '0x376dd6fc3c0071f4167092bd237e7a141767e4a3'
      cSCCsc: 060f28b8ab153c542bceff9c
    type: object
  SearchHit:
    description: An elasticsearch result for beacons
    required:
      - shDocId
    properties:
      shDocId:
        description: The identified for the DB
        example: docid
        type: string
      shScore:
        format: double
        type: number
      shSource:
        example:
          - NYC Beacon hub
          - t3k6pt76wv36tqrdevu
        minItems: 2
        items:
          - type: string
          - example: lpb2b3kosmdi53dg
            format: base32
            type: string
        maxItems: 2
        type: array
    example:
      shScore: 2.2342
      shDocId: docid
      shSource:
        - NYC Beacon hub
        - t3k6pt76vc4g0w32ymp
    type: object
  DocId:
    description: The identified for the DB
    example: docid
    type: string
  FoamSearchResult:
    example:
      - NYC Beacon hub
      - t3k6pt76wv36tqrdevu
    minItems: 2
    items:
      - type: string
      - example: lpb2b3kosmdi53dg
        format: base32
        type: string
    maxItems: 2
    type: array
  Authentication:
    description: The authentication parameters coming from Metamask or uPort
    required:
      - authenticationAddress
      - authenticationMessage
      - authenticationSignature
    properties:
      authenticationAddress:
        example: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
        format: base16
        type: string
      authenticationMessage:
        description: A hexstring
        example: '0xabba666deadbeef'
        format: base16
        type: string
      authenticationSignature:
        description: A hexstring
        example: '0xabba666deadbeef'
        format: base16
        type: string
    example:
      authenticationSignature: 5f5daf8
      authenticationAddress: '0x278d55cb3682cfab8cf46c0a6cdba19f3ed43063'
      authenticationMessage: bc11e1
    type: object
securityDefinitions:
  JwtSecurity:
    in: header
    name: Authorization
    type: apiKey
    description: JSON Web Token-based API key
tags:
  - name: foam
